# Generated by Django 5.0.7 on 2026-02-07 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_father_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadharcard',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aadhar', to='testapp.person'),
        ),
    ]
